name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Configure for project with custom domain already set up
          static_site_generator: "vite"
          
      - name: Install dependencies
        run: cd gacha-web && bun install
        
      - name: Build
        run: |
          echo "Starting build process..."
          cd gacha-web
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Running build command..."
          bun run build
          echo "Build completed. Content of dist directory:"
          ls -la dist
        
      - name: Fix base path
        # Add base: '/gacha-roller/' to the vite.config.ts if needed
        run: |
          echo "Checking and fixing base path if needed..."
          cd gacha-web
          echo "vite.config.ts content:"
          cat vite.config.ts
          
          if ! grep -q "base:" "vite.config.ts"; then
            echo "Base path not found, adding it..."
            sed -i "s/plugins: \[react()\],/plugins: [react()],\n  base: '\/gacha-roller\/',/" vite.config.ts
            echo "Updated vite.config.ts:"
            cat vite.config.ts
            echo "Rebuilding with updated config..."
            bun run build
            echo "Rebuild completed. Content of dist directory:"
            ls -la dist
          else
            echo "Base path already exists in config"
          fi
          
      - name: Upload artifact
        run: |
          echo "Preparing to upload artifact..."
          echo "Content of gacha-web/dist directory:"
          ls -la ./gacha-web/dist
        
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gacha-web/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deployment preparation
        run: echo "Preparing to deploy to GitHub Pages at https://crohnos.github.io/gacha-roller/"
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Deployment completed
        run: |
          echo "Deployment completed successfully!"
          echo "Your site is now available at: ${{ steps.deployment.outputs.page_url }}"